### ISSUE TITLE
i can't build

### ISSUE THREAD

**Issue by masbog** [dhruv-kumar-jha/graphql-doc#2]
> MacBook-Pro:graphql-doc masbog$ yarn build
> yarn run v1.3.2
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> Module not found: Error: Can't resolve 'global/Store' in '/Users/xxx/GitHub/graphql-doc/src'
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

how to fix it? thanks

**Comment by StefanJanssen95** [comment]
Same issue here

**Comment by dhruv-kumar-jha** [comment]
`.env` file was missing as it was ignored in `.gitignore`,

Removing it from .gitignore and adding the .env file fixed the issue.

**Comment by masbog** [comment]
thank you @dhruv-kumar-jha
